const mongoose = require('mongoose');

const CardSchema = new mongoose.Schema({
  object: String,
  id: String,
  oracle_id: String,
  multiverse_ids: [String],
  name: String,
  lang: String,
  released_at: String,
  uri: String,
  scryfall_uri: String,
  layout: String,
  highres_image: Boolean,
  image_uris: Object,
  mana_cost: String,
  cmc: Number,
  type_line: String,
  power: Number,
  toughness: Number,
  colors: [String],
  color_identity: [String],
  card_faces: [Object],
  legalities: Object,
  games: [String],
  reserved: Boolean,
  foil: Boolean,
  nonfoil: Boolean,
  oversized: Boolean,
  promo: Boolean,
  reprint: Boolean,
  variation: Boolean,
  set: String,
  set_name: String,
  set_type: String,
  set_uri: String,
  set_search_uri: String,
  scryfall_set_uri: String,
  rulings_uri: String,
  prints_search_uri: String,
  collector_number: String,
  digital: Boolean,
  rarity: String,
  card_back_id: String,
  artist: String,
  artist_ids: [String],
  illustration_id: String,
  border_color: String,
  frame: String,
  full_art: Boolean,
  textless: Boolean,
  booster: Boolean,
  story_spotlight: Boolean,
  promo_types: [String],
  edhrec_rank: Number,
  related_uris: Object
});

module.exports = Card = mongoose.model('card', CardSchema);
